WEB SCRAPING

IMOPRTING  IMPORTANT LIBARARIES

In [9]:
from bs4 import BeautifulSoup
import requests as re
import pandas as pd

Making a GET request
check status code for response received
success code - 200

In [11]:
webpage=re.get("https://stats.espncricinfo.com/ci/content/records/83548.html")
print(webpage)

<Response [200]>

In [12]:

record=BeautifulSoup(webpage.content)
table=record.find_all("table")
list=[]

In [13]:
for i in table:
    for j in i.find_all("td"):
        list.append(j.text.replace("\n", " "))
print(list)
Player_Name=list[0:len(list):15]
Player_Name1=Player_Name[0:92]
Career_Span=list[1:len(list):15]
Career_Span1=Career_Span[0:92]
Matches=list[2:len(list):15]
Matches1=Matches[0:92]
Innings=list[3:len(list):15]
Innings1=Innings[0:92]
Not_Out=list[4:len(list):15]
Not_Out1=Not_Out[0:92]
Highest=list[5:len(list):15]
Highest1=Highest[0:92]
Average=list[7:len(list):15]
Average1=Average[0:92]
Ball_Faced=list[8:len(list):15]
Ball_Faced1=Ball_Faced[0:92]
Strike_Rate=list[9:len(list):15]
Strike_Rate1=Strike_Rate[0:92]
Century=list[10:len(list):15]
Century1=Century[0:92]
Half_Century=list[11:len(list):15]
Half_Century1=Half_Century[0:92]
Ducks=list[12:len(list):15]
Ducks1=Ducks[0:92]
Fours=list[13:len(list):15]
Fours1=Fours[0:92]
Sixes=list[14:len(list):15]
Sixes1=Sixes[0:92]

['SR Tendulkar (IND)', '1989-2012', '463', '452', '41', '18426', '200*', '44.83', '21368', '86.23', '49', '96', '20', '2016', '195', 'KC Sangakkara (Asia/ICC/SL)', '2000-2015', '404', '380', '41', '14234', '169', '41.98', '18048', '78.86', '25', '93', '15', '1385', '88', 'RT Ponting (AUS/ICC)', '1995-2012', '375', '365', '39', '13704', '164', '42.03', '17046', '80.39', '30', '82', '20', '1231', '162', 'ST Jayasuriya (Asia/SL)', '1989-2011', '445', '433', '18', '13430', '189', '32.36', '14725', '91.20', '28', '68', '34', '1500', '270', 'V Kohli (IND)', '2008-2023', '274', '265', '40', '12898', '183', '57.32', '13776', '93.62', '46', '65', '15', '1211', '138', 'DPMD Jayawardene (Asia/SL)', '1998-2015', '448', '418', '39', '12650', '144', '33.37', '16020', '78.96', '19', '77', '28', '1119', '76', 'Inzamam-ul-Haq (Asia/PAK)', '1991-2007', '378', '350', '53', '11739', '137*', '39.52', '15812', '74.24', '10', '83', '20', '971', '144', 'JH Kallis (Afr/ICC/SA)', '1996-2014', '328', '314', '53', '11579', '139', '44.36', '15885', '72.89', '17', '86', '17', '911', '137', 'SC Ganguly (Asia/IND)', '1992-2007', '311', '300', '23', '11363', '183', '41.02', '15416', '73.70', '22', '72', '16', '1122', '190', 'R Dravid (Asia/ICC/IND)', '1996-2011', '344', '318', '40', '10889', '153', '39.16', '15285', '71.23', '12', '83', '13', '950', '42', 'MS Dhoni (Asia/IND)', '2004-2019', '350', '297', '84', '10773', '183*', '50.57', '12303', '87.56', '10', '73', '10', '826', '229', 'CH Gayle (ICC/WI)', '1999-2019', '301', '294', '17', '10480', '215', '37.83', '12019', '87.19', '25', '54', '25', '1128', '331', 'BC Lara (ICC/WI)', '1990-2007', '299', '289', '32', '10405', '169', '40.48', '13086', '79.51', '19', '63', '16', '1042', '133', 'TM Dilshan (SL)', '1999-2016', '330', '303', '41', '10290', '161*', '39.27', '11933', '86.23', '22', '47', '11', '1111', '55', 'RG Sharma (IND)', '2007-2023', '243', '236', '34', '9825', '264', '48.63', '10914', '90.02', '30', '48', '14', '900', '275', 'Mohammad Yousuf (Asia/PAK)', '1998-2010', '288', '273', '40', '9720', '141*', '41.71', '12942', '75.10', '15', '64', '15', '785', '90', 'AC Gilchrist (AUS/ICC)', '1996-2008', '287', '279', '11', '9619', '172', '35.89', '9922', '96.94', '16', '55', '19', '1162', '149', 'AB de Villiers (Afr/SA)', '2005-2018', '228', '218', '39', '9577', '176', '53.50', '9473', '101.09', '25', '53', '7', '840', '204', 'M Azharuddin (IND)', '1985-2000', '334', '308', '54', '9378', '153*', '36.92', '12669', '74.02', '7', '58', '9', '622+', '77+', 'PA de Silva (SL)', '1984-2003', '308', '296', '30', '9284', '145', '34.90', '11443', '81.13', '11', '64', '17', '712+', '102+', 'Saeed Anwar (PAK)', '1989-2003', '247', '244', '19', '8824', '194', '39.21', '10938', '80.67', '20', '43', '15', '938', '97', 'S Chanderpaul (WI)', '1994-2011', '268', '251', '40', '8778', '150', '41.60', '12408', '70.74', '11', '59', '6', '722', '85', 'Yuvraj Singh (Asia/IND)', '2000-2017', '304', '278', '40', '8701', '150', '36.55', '9924', '87.67', '14', '52', '18', '908', '155', 'DL Haynes (WI)', '1978-1994', '238', '237', '28', '8648', '152*', '41.37', '13707', '63.09', '17', '57', '13', '768+', '53+', 'LRPL Taylor (NZ)', '2006-2022', '236', '220', '39', '8607', '181*', '47.55', '10330', '83.32', '21', '51', '9', '713', '147', 'MS Atapattu (SL)', '1990-2007', '268', '259', '32', '8529', '132*', '37.57', '12594', '67.72', '11', '59', '13', '734', '15', 'ME Waugh (AUS)', '1988-2002', '244', '236', '20', '8500', '173', '39.35', '11053', '76.90', '18', '50', '16', '651', '57', 'V Sehwag (Asia/ICC/IND)', '1999-2013', '251', '245', '9', '8273', '219', '35.05', '7929', '104.33', '15', '38', '14', '1132', '136', 'Tamim Iqbal (BAN)', '2007-2023', '237', '235', '12', '8210', '158', '36.81', '10449', '78.57', '14', '55', '19', '908', '103', 'HM Amla (SA)', '2008-2019', '181', '178', '14', '8113', '159', '49.46', '9178', '88.39', '27', '39', '4', '822', '53', 'HH Gibbs (SA)', '1996-2010', '248', '240', '16', '8094', '175', '36.13', '9721', '83.26', '21', '37', '22', '930', '128', 'Shahid Afridi (Asia/ICC/PAK)', '1996-2015', '398', '369', '27', '8064', '124', '23.57', '6892', '117.00', '6', '39', '30', '730', '351', 'SP Fleming (ICC/NZ)', '1994-2007', '280', '269', '21', '8037', '134*', '32.40', '11242', '71.49', '8', '49', '17', '823', '63', 'MJ Clarke (AUS)', '2003-2015', '245', '223', '44', '7981', '130', '44.58', '10104', '78.98', '8', '58', '10', '665', '53', 'EJG Morgan (ENG/IRE)', '2006-2022', '248', '230', '34', '7701', '148', '39.29', '8447', '91.16', '14', '47', '18', '654', '220', 'SR Waugh (AUS)', '1986-2002', '325', '288', '58', '7569', '120*', '32.90', '9971', '75.91', '3', '45', '15', '530', '68', 'Shoaib Malik (PAK)', '1999-2019', '287', '258', '40', '7534', '143', '34.55', '9199', '81.90', '9', '44', '15', '603', '113', 'A Ranatunga (SL)', '1982-1999', '269', '255', '47', '7456', '131*', '35.84', '9571', '77.90', '4', '49', '18', '523+', '64+', 'Javed Miandad (PAK)', '1975-1996', '233', '218', '41', '7381', '119*', '41.70', '11014', '67.01', '8', '50', '8', '445+', '44+', 'MJ Guptill (NZ)', '2009-2022', '198', '195', '19', '7346', '237*', '41.73', '8415', '87.29', '18', '39', '16', '750', '187', 'Younis Khan (PAK)', '2000-2015', '265', '255', '23', '7249', '144', '31.24', '9628', '75.29', '7', '48', '22', '578', '56', 'Saleem Malik (PAK)', '1982-1999', '283', '256', '38', '7170', '102', '32.88', '9383', '76.41', '5', '47', '19', '514+', '34+', 'NJ Astle (NZ)', '1995-2007', '223', '217', '14', '7090', '145*', '34.92', '9760', '72.64', '16', '41', '19', '720', '86', 'Shakib Al Hasan (BAN)', '2006-2023', '230', '217', '30', '7086', '134*', '37.89', '8580', '82.58', '9', '53', '12', '643', '46', 'Mushfiqur Rahim (BAN)', '2006-2023', '245', '229', '38', '7045', '144', '36.88', '8864', '79.47', '9', '43', '11', '558', '91', 'GC Smith (Afr/SA)', '2002-2013', '197', '194', '10', '6989', '141', '37.98', '8648', '80.81', '10', '47', '8', '788', '44', 'WU Tharanga (Asia/SL)', '2005-2019', '235', '223', '17', '6951', '174*', '33.74', '9155', '75.92', '15', '37', '17', '798', '52', 'MG Bevan (AUS)', '1994-2004', '232', '196', '67', '6912', '108*', '53.58', '9320', '74.16', '6', '46', '5', '450', '21', 'G Kirsten (SA)', '1993-2003', '185', '185', '19', '6798', '188*', '40.95', '9436', '72.04', '13', '45', '11', '659', '20', 'S Dhawan (IND)', '2010-2022', '167', '164', '10', '6793', '143', '44.11', '7436', '91.35', '17', '39', '5', '842', '79', 'A Flower (ZIM)', '1992-2003', '213', '208', '16', '6786', '145', '35.34', '9097', '74.59', '4', '55', '13', '532+', '26+', 'IVA Richards (WI)', '1975-1991', '187', '167', '24', '6721', '189*', '47.00', '7451', '90.20', '11', '45', '7', '600+', '126+', 'BRM Taylor (ZIM)', '2004-2021', '205', '203', '15', '6684', '145*', '35.55', '8721', '76.64', '11', '39', '15', '599', '106', 'Mohammad Hafeez (PAK)', '2003-2019', '218', '216', '15', '6614', '140*', '32.90', '8633', '76.61', '11', '38', '19', '664', '110', 'GW Flower (ZIM)', '1992-2010', '221', '214', '18', '6571', '142*', '33.52', '9723', '67.58', '6', '40', '18', '557+', '37+', 'Ijaz Ahmed (PAK)', '1986-2000', '250', '232', '29', '6564', '139*', '32.33', '8174', '80.30', '10', '37', '14', '531+', '87+', 'KS Williamson (NZ)', '2010-2023', '161', '153', '16', '6554', '148', '47.83', '8094', '80.97', '13', '42', '5', '594', '51', 'AR Border (AUS)', '1979-1994', '273', '252', '39', '6524', '127*', '30.62', '9134', '71.42', '3', '39', '11', '500', '43', 'RB Richardson (WI)', '1983-1996', '224', '217', '30', '6248', '122', '33.41', '9801', '63.74', '5', '44', '8', '541+', '54+', 'JE Root (ENG)', '2013-2022', '158', '147', '23', '6207', '133*', '50.05', '7140', '86.93', '16', '36', '7', '496', '46', 'ML Hayden (AUS/ICC)', '1993-2008', '161', '155', '15', '6133', '181*', '43.80', '7767', '78.96', '10', '36', '9', '636', '87', 'BB McCullum (NZ)', '2002-2016', '260', '228', '28', '6083', '166', '30.41', '6312', '96.37', '5', '32', '20', '577', '200', 'DM Jones (AUS)', '1984-1994', '164', '161', '25', '6068', '145', '44.61', '8362', '72.56', '7', '46', '6', '380+', '64+', 'DA Warner (AUS)', '2009-2023', '142', '140', '6', '6030', '179', '45.00', '6337', '95.15', '19', '27', '3', '639', '92', 'Q de Kock (SA)', '2013-2023', '140', '140', '7', '5966', '178', '44.85', '6209', '96.08', '17', '29', '4', '687', '93', 'DC Boon (AUS)', '1984-1995', '181', '177', '16', '5964', '122', '37.04', '9157', '65.13', '5', '37', '6', '494', '16', 'JN Rhodes (SA)', '1992-2003', '245', '220', '51', '5935', '121', '35.11', '7336', '80.90', '2', '33', '12', '392', '47', 'AD Mathews (SL)', '2008-2023', '220', '190', '48', '5853', '139*', '41.21', '7037', '83.17', '3', '40', '16', '464', '89', 'Ramiz Raja (PAK)', '1985-1997', '198', '197', '15', '5841', '119*', '32.09', '9226', '63.31', '9', '31', '15', '469+', '14+', 'RR Sarwan (WI)', '2000-2013', '181', '169', '33', '5804', '120*', '42.67', '7663', '75.74', '5', '38', '8', '480', '58', 'CL Hooper (WI)', '1987-2003', '227', '206', '43', '5761', '113*', '35.34', '7517', '76.63', '7', '29', '7', '409', '65', 'SR Watson (AUS)', '2002-2015', '190', '169', '27', '5757', '185*', '40.54', '6365', '90.44', '9', '33', '12', '570', '131', 'H Masakadza (ZIM)', '2001-2019', '209', '208', '4', '5658', '178*', '27.73', '7728', '73.21', '5', '34', '15', '585', '86', 'SK Raina (IND)', '2005-2018', '226', '194', '35', '5615', '116*', '35.31', '6005', '93.50', '5', '36', '14', '476', '120', 'MN Samuels (WI)', '2000-2018', '207', '196', '26', '5606', '133*', '32.97', '7463', '75.11', '10', '30', '11', '526', '118', 'WJ Cronje (SA)', '1992-2000', '188', '175', '31', '5565', '112', '38.64', '7277', '76.47', '2', '39', '8', '366', '94', 'F du Plessis (SA)', '2011-2019', '143', '136', '20', '5507', '185', '47.47', '6215', '88.60', '12', '35', '3', '495', '66', 'MEK Hussey (AUS)', '2004-2012', '185', '157', '44', '5442', '109*', '48.15', '6243', '87.16', '3', '39', '3', '383', '80', 'IR Bell (ENG)', '2004-2015', '161', '157', '14', '5416', '141', '37.87', '7019', '77.16', '4', '35', '6', '525', '32', 'AJ Finch (AUS)', '2013-2022', '146', '142', '3', '5406', '153*', '38.89', '6162', '87.73', '17', '30', '16', '532', '129', 'A Jadeja (IND)', '1992-2000', '196', '179', '36', '5359', '119', '37.47', '7678', '69.79', '6', '30', '10', '366', '85', 'DR Martyn (AUS)', '1992-2006', '208', '182', '51', '5346', '144*', '40.80', '6877', '77.73', '5', '37', '10', '441', '22', 'PR Stirling (IRE)', '2008-2023', '145', '140', '3', '5259', '177', '38.38', '6086', '86.41', '13', '26', '11', '564', '122', 'G Gambhir (IND)', '2003-2013', '147', '143', '11', '5238', '150*', '39.68', '6144', '85.25', '11', '34', '11', '561', '17', 'ADR Campbell (ZIM)', '1992-2003', '188', '184', '14', '5185', '131*', '30.50', '7834', '66.18', '7', '30', '11', '427+', '44+', 'RS Mahanama (SL)', '1986-1999', '213', '198', '23', '5162', '119*', '29.49', '8521', '60.57', '4', '35', '15', '331+', '17+', 'CG Greenidge (WI)', '1975-1991', '128', '127', '13', '5134', '133*', '45.03', '7908', '64.92', '11', '31', '3', '470+', '81+', 'Misbah-ul-Haq (PAK)', '2002-2015', '162', '149', '31', '5122', '96*', '43.40', '6945', '73.75', '0', '42', '6', '342', '83', 'JP Duminy (SA)', '2004-2019', '199', '179', '40', '5117', '150*', '36.81', '6052', '84.55', '4', '27', '7', '347', '75', 'PD Collingwood (ENG)', '2001-2011', '197', '181', '37', '5092', '120*', '35.36', '6614', '76.98', '5', '26', '7', '365', '74', 'A Symonds (AUS)', '1998-2009', '198', '161', '33', '5088', '156', '39.75', '5504', '92.44', '6', '30', '15', '449', '103', 'Abdul Razzaq (Asia/PAK)', '1996-2011', '265', '228', '57', '5080', '112', '29.70', '6252', '81.25', '3', '23', '14', '382', '124', '    By default, the shading indicates records from the past week, or failing that, the most recent entry.   ', ' Adjust: most recent    | past week    | past month    | past 6 months    | past year    | 4 years    | 10 years    | 25 years ', ' Records includes the following current or recent matches: ', " Nepal v Oman at Kirtipur, ACC Men's Premier Cup 7th match, Apr 21, 2023 [ODI # 4568] ", ' Canada v Papua New Guinea at Windhoek, ICC Cricket World Cup Qualifier Play-off 15th match, Apr 5, 2023 [ODI # 4567] ', ' Jersey v United Arab Emirates at Windhoek, ICC Cricket World Cup Qualifier Play-off 14th match, Apr 5, 2023 [ODI # 4566] ']

In [14]:

df=pd.DataFrame({})
df["Player_Name"]=Player_Name1
df["Career_Span"]=Career_Span1
df["Matches"]=Matches1
df["Innings"]=Innings1
df["Not_Out"]=Not_Out1
df["Highest Score"]=Highest1
df["Average"]=Average1
df["Balls_Faced"]=Ball_Faced1
df["Strike_Rate"]=Strike_Rate1
df["Century"]=Century1
df["Half_Century"]=Half_Century1
df["Ducks"]=Ducks1
df["Fours"]=Fours1
df["Sixes"]=Sixes1
print(df)

                    Player_Name Career_Span Matches Innings Not_Out  \
0            SR Tendulkar (IND)   1989-2012     463     452      41
1   KC Sangakkara (Asia/ICC/SL)   2000-2015     404     380      41
2          RT Ponting (AUS/ICC)   1995-2012     375     365      39
3       ST Jayasuriya (Asia/SL)   1989-2011     445     433      18
4                 V Kohli (IND)   2008-2023     274     265      40
..                          ...         ...     ...     ...     ...
87          Misbah-ul-Haq (PAK)   2002-2015     162     149      31
88               JP Duminy (SA)   2004-2019     199     179      40
89         PD Collingwood (ENG)   2001-2011     197     181      37
90              A Symonds (AUS)   1998-2009     198     161      33
91      Abdul Razzaq (Asia/PAK)   1996-2011     265     228      57

   Highest Score Average Balls_Faced Strike_Rate Century Half_Century Ducks  \
0          18426   44.83       21368       86.23      49           96    20
1          14234   41.98       18048       78.86      25           93    15
2          13704   42.03       17046       80.39      30           82    20
3          13430   32.36       14725       91.20      28           68    34
4          12898   57.32       13776       93.62      46           65    15
..           ...     ...         ...         ...     ...          ...   ...
87          5122   43.40        6945       73.75       0           42     6
88          5117   36.81        6052       84.55       4           27     7
89          5092   35.36        6614       76.98       5           26     7
90          5088   39.75        5504       92.44       6           30    15
91          5080   29.70        6252       81.25       3           23    14

   Fours Sixes
0   2016   195
1   1385    88
2   1231   162
3   1500   270
4   1211   138
..   ...   ...
87   342    83
88   347    75
89   365    74
90   449   103
91   382   124

[92 rows x 14 columns]

In [16]:
df

,Player_Name,Career_Span,Matches,Innings,Not_Out,Highest Score,Average,Balls_Faced,Strike_Rate,Century,Half_Century,Ducks,Fours,Sixes
0,SR Tendulkar (IND),1989-2012,463,452,41,18426,44.83,21368,86.23,49,96,20,2016,195
1,KC Sangakkara (Asia/ICC/SL),2000-2015,404,380,41,14234,41.98,18048,78.86,25,93,15,1385,88
2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,42.03,17046,80.39,30,82,20,1231,162
3,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,32.36,14725,91.20,28,68,34,1500,270
4,V Kohli (IND),2008-2023,274,265,40,12898,57.32,13776,93.62,46,65,15,1211,138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Misbah-ul-Haq (PAK),2002-2015,162,149,31,5122,43.40,6945,73.75,0,42,6,342,83
88,JP Duminy (SA),2004-2019,199,179,40,5117,36.81,6052,84.55,4,27,7,347,75
89,PD Collingwood (ENG),2001-2011,197,181,37,5092,35.36,6614,76.98,5,26,7,365,74
90,A Symonds (AUS),1998-2009,198,161,33,5088,39.75,5504,92.44,6,30,15,449,103
91,Abdul Razzaq (Asia/PAK),1996-2011,265,228,57,5080,29.70,6252,81.25,3,23,14,382,124